import type { Section } from './client-guidelines-content';

export const rulesRegulationsDocumentTitle = 'Rules & Regulations';

export const rulesRegulationsDocumentIntro =
  'Please read all of the following in great detail as you start planning your event. Feel free to contact our event team with any questions or concerns at 212.971.5353.';

export const rulesRegulationsContent: Section[] = [
  {
    id: 'overview-prohibited',
    title: 'Overview, Restrictions & Prohibited Items',
    content: [
      `48 Wall Street grants their exclusive vendors the privilege to provide event planning and production services throughout the space, which includes audio visual, lighting, staging, custom fabrication, décor, floral, entertainment, all rentals, musical entertainment, printing, tenting, and extra entertainment.`,
      `48 Wall Street is a landmark building; restrictions apply. Nothing can be placed on the walls, columns, revolving door, etc. without prior consent from 48 Wall Street. All visitors must check in with the security desk and event team.`,
      `Safety, Fire Code & Insurance Requirements — to ensure the safety of all guests, vendors, and staff, and to preserve the integrity of the historic 48 Wall Street property, all event professionals, vendors, exhibitors, and contractors must comply with the following safety, fire code, and insurance requirements.`,
      `Prohibited Items — the following are strictly prohibited unless expressly authorized in writing by Venue Management and all applicable governing authorities:`,
      `• Pyrotechnics of any kind`,
      `• Open flames, including candles not enclosed in approved glass containers`,
      `• Sterno fuel, butane burners, propane tanks, or other open-flame cooking devices`,
      `• Fireworks, sparklers, and flame effects`,
      `• Smoke, fog, haze, or atmospheric effects without prior approval`,
      `• Confetti cannons, glitter, or similar materials`,
      `• Hazardous or combustible materials`,
      `• Any item that may damage or compromise the historic building or violate applicable fire and life safety codes`,
      `Any unauthorized use of prohibited items may result in immediate removal from the venue, cancellation of the event, and financial responsibility for any resulting damages or penalties.`,
    ],
    requiresInitials: true,
  },
  {
    id: 'fire-coi-entertainment',
    title: 'Fire Safety, Insurance & Entertainment',
    content: [
      `Fire Safety Compliance — all decorative materials, drapery, scenic elements, soft goods, and fabrics brought into the venue must:`,
      `• Be inherently flame-resistant or professionally treated with an approved fire-retardant solution.`,
      `• Be accompanied by a valid Fire Retardant Certificate upon request.`,
      `• Comply with all applicable FDNY regulations and local fire codes.`,
      `Venue Management reserves the right to inspect and reject any material that does not meet required safety standards.`,
      `Certificates of Insurance (COI) — all outside vendors, contractors, exhibitors, entertainers, and service providers must provide a COI meeting the venue's insurance requirements:`,
      `• COI must be submitted no later than three (3) weeks prior to the event date.`,
      `• Coverage limits must meet the minimum insurance requirements established by 48 Wall Street.`,
      `• 48 Wall Street and its ownership and management entities must be listed as Additional Insured, when required.`,
      `• Vendors will not be permitted to access the property without an approved Certificate of Insurance.`,
      `COIs should be submitted electronically to: info@48WallNYC.com`,
      `Entertainment & Performance Insurance — all performers, entertainers, production companies, speakers, exhibitors, specialty acts, DJs, bands, and interactive experiences must provide a current Certificate of General Liability Insurance, execute all required Venue performance and production agreements and liability waivers, and comply with all applicable federal, state, and local safety regulations and Venue operational policies.`,
      `Any outside audio, audiovisual, or production vendor may not connect, patch into, or utilize the Venue's existing audio systems, sound boards, lighting systems, video infrastructure, or production equipment without the prior written approval of Venue Management at least fourteen (14) days before the Event Date.`,
    ],
    requiresInitials: true,
  },
  {
    id: 'enforce-audio',
    title: 'Right to Enforce & Audio Production',
    content: [
      `If an outside audio or production vendor is approved to integrate with the Venue's audiovisual systems, additional technical coordination, engineering, labor, equipment, and patching fees may apply. All associated costs shall be the responsibility of the Client and billed per the Venue's current production and technical services schedule.`,
      `The Venue reserves the right to require the use of its exclusive or designated audiovisual and production partners whenever necessary to protect the Venue's equipment, maintain operational standards, and ensure the safe and successful execution of the Event.`,
      `Additional documentation, technical riders, production schedules, equipment specifications, and insurance requirements may be required depending on the scope and nature of the performance or production.`,
      `Right to Enforce — 48 Wall Street reserves the right to deny access, suspend activities, or remove any vendor, contractor, or performer who fails to comply with these Safety, Fire Code, and Insurance Requirements. Compliance is mandatory and a condition of access to the property.`,
      `Audio, Video & Lighting Production Guidelines — all audiovisual, lighting, and production services are managed exclusively by the venue's approved production partners to ensure seamless integration with the building's infrastructure and protect the historic property.`,
      `Audio Production — all audio systems, microphones, sound reinforcement, playback, and technical infrastructure must be provided and operated by the venue's exclusive audiovisual partner.`,
      `Audio Requirements:`,
      `• Outside audio equipment is not permitted without prior written approval from Venue Management.`,
      `• A 48 Wall Street Lead Audio Engineer (A1) is required for all events utilizing venue audio systems.`,
      `• Clients may retain their own Technical Director, Show Caller, or Lead A1 to supervise operations; however, all venue audio systems remain under the direction of the venue's assigned A1.`,
      `• Any additional specialty audio requirements must be submitted no later than two (2) weeks prior to the event date for engineering review and approval.`,
    ],
    requiresInitials: true,
  },
  {
    id: 'video-lighting',
    title: 'Video & Lighting Production',
    content: [
      `Video Production — video playback, presentation systems, LED displays, projection, switching, recording, livestreaming, and video engineering are exclusively managed by the venue's approved production partner.`,
      `Video Requirements:`,
      `• Outside video production equipment and operators are not permitted without prior written approval.`,
      `• Final presentation materials, videos, graphics, and playback content must be submitted no later than one (1) week prior to the event.`,
      `• Accepted file formats: MOV (H.264), Microsoft PowerPoint, Apple Keynote.`,
      `• Built-in projection screens measure 62" × 100" with a native 4:3 aspect ratio; custom formatting or conversion may be required.`,
      `• Final media files should be fully tested before submission. Revisions received after the deadline may incur additional production charges.`,
      `• Recorded event content, edited media, or video deliverables will not be released until all outstanding invoices are paid in full.`,
      `Lighting Production — architectural, theatrical, intelligent, pin-spotting, scenic, and special effects lighting are provided exclusively by the venue's approved lighting partner.`,
      `Lighting Requirements:`,
      `• Outside lighting fixtures, control systems, and lighting vendors are prohibited unless approved in writing by Venue Management.`,
      `• Clients must submit all lighting requests, color palettes, branding requirements, scenic renderings, and production specifications at least two (2) weeks prior to the event.`,
      `• Custom lighting designs are subject to venue engineering review for compatibility with the building's historic architecture and electrical infrastructure.`,
      `Production Coordination — all technical production schedules, show flows, media timelines, rehearsals, and engineering requirements should be coordinated with the 48 Wall Street Production Team well in advance of the event.`,
    ],
    requiresInitials: true,
  },
  {
    id: 'power-network',
    title: 'Electrical Power & Connectivity',
    content: [
      `Electrical Power & Connectivity Guidelines — electrical distribution and network services are managed by our exclusive production partners; advance planning allows proper allocation of power and network resources while protecting the venue's historic infrastructure.`,
      `Electrical Power Requirements — all temporary electrical services, production power distribution, and dedicated circuits must be coordinated through the venue's exclusive production partner.`,
      `Power Requirements:`,
      `• All electrical requirements (staging, audiovisual, lighting, catering, exhibitor, production) must be submitted no later than two (2) weeks prior to the event for engineering review and approval.`,
      `• Temporary power distribution, dedicated circuits, and specialty electrical services are provided exclusively by the venue's approved production partner.`,
      `• Additional power drops, dedicated circuits, and high-capacity electrical services are available and may be subject to additional fees.`,
      `• Plugging equipment into existing wall outlets, house circuits, or electrical panels without prior written authorization is strictly prohibited.`,
      `• Any unauthorized electrical connections may be disconnected immediately to protect guest safety and the building's electrical infrastructure.`,
      `• All electrical equipment brought into the venue must comply with applicable electrical codes and safety regulations.`,
      `Internet & Wi-Fi Services — 48 Wall Street offers reliable wireless connectivity throughout the venue for general guest internet access.`,
      `Network Services:`,
      `• A shared venue Wi-Fi network is available throughout the property for standard guest use.`,
      `• Private, secure wireless networks, dedicated bandwidth, hardwired internet, VLANs, and custom network configurations are available upon request for corporate meetings, livestreams, hybrid conferences, media events, and mission-critical presentations.`,
      `• Requests for private networks or dedicated internet services should be submitted at least two (2) weeks prior to the event and may incur additional service fees.`,
      `• Clients requiring livestreaming, webcasting, hybrid platforms, or other high-bandwidth applications are strongly encouraged to coordinate technical requirements with the 48 Wall Street Production Team.`,
    ],
    requiresInitials: true,
  },
  {
    id: 'decor-floral',
    title: 'Décor, Floral, Rentals & Scenic',
    content: [
      `Our engineering professionals will work with your production team to ensure all electrical and network services support a seamless, secure, and successful event experience.`,
      `Décor, Floral, Rentals & Scenic Production Guidelines — all décor, floral, rental, scenic, and fabrication services are managed exclusively through the venue's approved event partners to ensure quality, coordination, and preservation of the historic architecture.`,
      `Décor & Floral Design — our exclusive design partners create bespoke event environments complementing the venue while reflecting your brand and objectives. Design services include: Luxury Floral Installations; Seasonal & Themed Décor; Corporate Branding & Environmental Design; Custom Tablescapes; Entrance Features & Guest Arrival Experiences; Holiday Décor; Lounge Styling; Stage & Presentation Design.`,
      `Please note:`,
      `• Outside décor and floral vendors are not permitted without prior written approval from Venue Management.`,
      `• All décor installations must comply with the venue's Historic Landmark Preservation Guidelines.`,
      `Event Rentals — our exclusive rental partner provides a comprehensive inventory of luxury furnishings and event equipment designed specifically for 48 Wall Street.`,
    ],
    requiresInitials: true,
  },
  {
    id: 'rentals-scenic-catering',
    title: 'Rentals, Scenic Fabrication & Outside Catering',
    content: [
      `Available rental items include: Banquet & Conference Tables; Chiavari, Ballroom & Designer Chairs; Luxury Linens & Specialty Tabletop; Lounge Furniture; Bars & Back Bars; Soft Seating Collections; Specialty Furnishings; China, Glassware & Flatware; Kitchen Equipment; Pipe & Drape; Decorative Props & Accessories.`,
      `Our team will recommend furnishings that complement both the scale of your event and the architectural elegance of the venue.`,
      `Scenic Design, Staging & Custom Fabrication — the venue's exclusive production partner provides complete scenic production and custom fabrication for meetings, conferences, product launches, fashion shows, galas, exhibitions, and experiential events. Services include: Custom Scenic Fabrication; Presentation Staging; Fashion Runways; Stage Sets; Scenic Backdrops; Branded Environments; Experiential Installations; LED Scenic Integration; Custom Signage & Large-Format Graphics.`,
      `All custom scenic, staging, and fabrication requests should be submitted a minimum of three (3) weeks prior to the event date. Complex or large-scale productions may require additional planning time.`,
      `Outside Catering Guidelines — 48 Wall Street works with select approved outside caterers when authorized in writing by Venue Management. All caterers must comply with the venue's operating procedures, safety requirements, insurance standards, and historic landmark preservation guidelines.`,
    ],
    requiresInitials: true,
  },
  {
    id: 'catering-docs-compliance',
    title: 'Catering Documentation, Beverage & Compliance',
    content: [
      `Required Documentation — all approved outside caterers must submit the following no later than two (2) weeks prior to the event:`,
      `• Certificate of Insurance meeting venue requirements`,
      `• Any required catering permits or operating documentation`,
      `• Final catering floor plan and back-of-house layout`,
      `• Full equipment list for review and approval`,
      `• Staffing list and vendor arrival schedule`,
      `Beverage & Alcohol Policy — all liquor, wine, beer, spirits, and alcoholic beverage service must be provided exclusively through 48 Wall Street and its approved beverage program. Outside caterers are not permitted to provide, sell, serve, transport, or arrange alcoholic beverages unless expressly authorized in writing by Venue Management and ownership.`,
      `Equipment & Rentals — all catering equipment, kitchen equipment, tables, service stations, bars, back bars, rentals, and related infrastructure must be provided through 48 Wall Street's exclusive approved vendors unless otherwise approved in writing.`,
      `Cooking & Heating Equipment — only approved electric catering equipment is permitted. The following are strictly prohibited with no exceptions: open flame; Sterno; gas cooking equipment; propane tanks; butane burners; charcoal; fryers or cooking equipment requiring flame or fuel; any equipment that creates excessive smoke, grease, fumes, or fire risk.`,
      `48 Wall Street reserves the right to deny access, disconnect, or remove any unapproved equipment from the property.`,
      `Venue Compliance — all outside caterers must follow the venue's rules and regulations, including load-in/load-out procedures, landmark preservation guidelines, cleanliness standards, waste removal, security requirements, and all instructions issued by Venue Management. Failure to comply may result in removal from the property, additional charges, forfeiture of security deposit, and suspension from future approved vendor access.`,
    ],
    requiresInitials: true,
  },
];
